test: &test
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: boatest
  username: boauser
  password: Prof_H_No_Sn00p1ng
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: boadev
  username: boauser
  password: Prof_H_No_Sn00p1ng
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: boastage
  username: boauser
  password: Prof_H_No_Sn00p1ng
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: boaprod
  username: boauser
  password: Prof_H_No_Sn00p1ng
  pool: 5
  timeout: 5000

cucumber:
  <<: *test